Transform: 'AWS::Serverless-2016-10-31'
Parameters:
    SamMultipler:
        Description: "SAM multiplier. Make this really big to have a party :)"
        Type: "String"
    OriginUrl:
        Description: "The origin url to allow CORS requests from. This will be the base URL of your static SAM website."
        Type: "String"
Resources:
    GetNoteList:
        Type: AWS::Serverless::Function
        Properties:
            Handler: list.main
            Runtime: nodejs4.3
            CodeUri: ./
            Environment:
                Variables:
                    SAM_MULTIPLIER: !Ref SamMultipler
                    ORIGIN_URL: !Ref OriginUrl
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /notes
                  Method: get
                  Cors: true
                  Authorizer:
                    arn: arn:aws:cognito-idp:us-west-2:356202615186:userpool/us-west-2_9n1nwbjET
