Transform: 'AWS::Serverless-2016-10-31'
# Parameters:
#     SamMultipler:
#         Description: "SAM multiplier. Make this really big to have a party :)"
#         Type: "String"
#     OriginUrl:
#         # Description: "The origin url to allow CORS requests from. This will be the base URL of your static SAM website."
#         Description: "*"
#         Type: "String"
Resources:
    CreateNote:
        Type: AWS::Serverless::Function
        Properties:
            Handler: create.main
            Runtime: nnodejs6.10
            CodeUri: ./
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /notes
                  Method: post

    GetNote:
        Type: AWS::Serverless::Function
        Properties:
            Handler: get.main
            Runtime: nnodejs6.10
            CodeUri: ./
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /notes/{id}
                  Method: get

    GetNoteList:
        Type: AWS::Serverless::Function
        Properties:
            Handler: list.main
            Runtime: nnodejs6.10
            CodeUri: ./
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /notes
                  Method: get

    UpdateNote:
        Type: AWS::Serverless::Function
        Properties:
            Handler: update.main
            Runtime: nnodejs6.10
            CodeUri: ./
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /notes/{id}
                  Method: put

    DeleteNote:
        Type: AWS::Serverless::Function
        Properties:
            Handler: delete.main
            Runtime: nnodejs6.10
            CodeUri: ./
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /notes/{id}
                  Method: delete
                  
